print("Please input 2 numbers ")
x=float(input("please input 1st number : "))
y=float(input("please input 2nd number : "))
print(x,"+",y,"=",x+y)
print(x,"-",y,"=",x-y)
print(x,"x",y,"=",x*y)
print(x,"/",y,"=",x/y)